### ISSUE TITLE
410 error

### ISSUE THREAD

**Issue by guibor** [ddvk/rmapi#5]
When I run rmapi, I get this error after authenticating (pasting my one-time code):

ERROR: 2024/10/18 16:07:24 main.go:77: failed to build documents tree, last error: request failed with status 410

**Comment by bennofs** [comment]
For me, updating to the latest version (0.0.27.1) fixed that error. Which version are you using? (`rmapi version` to check)

**Comment by guibor** [comment]
It says "dev" (version = dev), isn't that weird? I followed the installation instructions
(this is also what's in version.go in the repository)

**Comment by Azeirah** [comment]
> It says "dev" (version = dev), isn't that weird? I followed the installation instructions (this is also what's in version.go in the repository)

It means that you installed it from source, instead of downloading it from the releases. You can't really see what version you're currently running, because version "dev" means "you built it yourself".

I suggest you try the latest release from the releases itself: https://github.com/ddvk/rmapi/releases/tag/v0.0.27.1 and see if you still have the same issue.

**Comment by guibor** [comment]
Just downloaded from the link you shared.
Still says dev when running rmapi (running directly in the directory where it was downloaded and unzipped)

**Comment by guibor** [comment]
It says 'dev' in version, but I think works - will check now

**Comment by Azeirah** [comment]
Weird that it's also still the dev version 😅

But hey, if it works 🤷‍♀️

**Comment by ddvk** [comment]
you sure you didn't download the original source and build it? also make sure you don't have the old one in you PATH somewhere
